### PR TITLE
refactor: setup SwiftUI

### PR DESCRIPTION
**Pull request by florentlotthepro**
## Changes description

Done all the setup to use `SwiftUI` in the project
- Move common code to a `VitaminCore` module.
- Keep `UIKit` code in the `Vitamin` module (`VitaminUIKit` folder). It was not moved to a `VitaminUIKit` module to avoid a breaking change.
- Create a `VitaminSwiftUI` module for `SwiftUI` part (with the foundations part to begin).
- Update documentation and showcase.

## Context

`SwiftUI` is a new Apple technology and will be used more and more so we need to be present on it.

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on an iPhone device/simulator.
- [x] I have tested on an iPad device/simulator.
- [x] If it includes design changes, please ask for a review with a core team designer.
- [x] Update CocoaPods spec.

## Does this introduce a breaking change?

- No

#### iPhone

Simulator Screen Shot - iPhone 11 - 2022-04-25 at 15 30 06

#### iPad

Simulator Screen Shot - iPad (7th generation) - 2022-04-25 at 15 31 11

### CODE REVIEW

**Review by daniel-dumortier — DISMISSED** [review]
I reviewed globally the files, et did not see any evident issue.
I built the showcase, and did not notice any issue.
I was able to integrate the branch to my app with cocoapods without breaking anything.
Except the build problem on Bitrise (but not linked to the code, in my opinion), everything is OK for me

**Review by daniel-dumortier — DISMISSED** [review]
Ok for me, great to have found the fix for building despite the iOS10 compatibility

**Comment by MARIEDELATTRE** [comment]
Hi guys thanks for this PR.
Here is my design review (I have checked in darkmode) :
• Assets: maybe it's on our side, but I think favicon shouldn't be transparent but white in background + favicon-black seem to not be black.
• Colors: it seems OK in darkmode please double-check with @simon if the last changes we made are ok like in borders.
• Icons: it's a bit blurry on my iphone is it normal?
• Radius: could you please display rectangles because I can't chek if 800 is ok because the radius is larger than the height of the frame (the last one seem weird).
• Shadows: I saw that we don't add the shadows in darkmode like in the wel library it seems ok, but maybe you want us to add them in the design lib to verify?
• Typography: bold equivalents are missing (footnote callout and body)

And it's details but the titles are sometimes plural sometimes singular I think it can be harmonized 🙂

**Review by baptistedajon — APPROVED** [review]
☯

**Review by daniel-dumortier — APPROVED** [review]
🤘

**Pull request merged**
