### PR TITLE
feat: add progress bar component

### LINKED ISSUE #12: feat: add progress bar component
**New component**

Add progress bar component.

**Documentation links**

- [Documentation](https://www.decathlon.design/726f8c765/p/2388f2-progress-bar-beta)
- [Figma](https://www.figma.com/file/cmZCNVet64UlDNnDDd4hDV/Vitamin-iOS-14-UI-kit-v0?node-id=565%3A1857)

### PR DESCRIPTION
**Pull request by daniel-dumortier**
### Changes Description
Here is a proposal of implementation for progress bars.
It handles the two variants (linear, circular), each sub-style (empty, image, percentage), size (small, medium, large) of them.
It also handles the progress type (determinate and indeterminate)

The Showcase has been updated to demonstrate all possible configurations for progressbar.

The documentation has been added, and the general Readme has been updated to reference this documentation.

- Close #12 

### Remarks
1 - there is still a SwiftLint warning regarding the file length. I decided not to fix it because it would require to :
- either create non relevant extension
- or artificially change access control of some properties to be able to put them in other files

2 - The content of this PR has already partially been reviewed by @florentlotthepro on the inner-source repo, I just refactored the showcase and doc parts, fixed @florentlotthepro feedbacks, and fixed some problems with dark mode

### CODE REVIEW

**Review by florentlotthepro — DISMISSED** [review]
You can maybe try to reduce `VitaminProgressbar` by extracting `linear` or `circular` code in an other file.
I think that you can also add the `final` keyword to your classes.

**Comment by daniel-dumortier** [comment]
I tried, but most of the code is organized with common functions for both variant, and a test on the variant in the body of the method.
Splitting it in two would require to break all the code, which IMHO is not worth just to reduce the file that is less than 100 lines above the suggested Swiftlint limit.

And when I try to move extensions in other files, I always struggle with private properties/functions, that are not visible. And I am not sure this is a good idea to reduce the access control just to match the Swiftlint rule about file size.

I was just able to extract colors in a separate file. And I extracted the background and label colors in this extension.

**Comment by florentlotthepro** [comment]
And for the `final` keyword to your classes?

**Comment by daniel-dumortier** [comment]
I add the final class on the `VitamoinProgressbart`class.

Did you mean to put it on Showcase classes ? If yes, I can do that, but I am not sure to get the point since they are classes of the Showcase, they won't be packaged and distributed, and thus, I am not really sur to understand who we would like to avoid subclassing these classes... ;)

**Comment by florentlotthepro** [comment]
With a lot of classes, it could speed up the build, it's principally for that.

**Review by florentlotthepro — APPROVED** [review]

**Comment by daniel-dumortier** [comment]
Honesttly, I did not know that. So let's go for it !

**Review by florentlotthepro — DISMISSED** [review]
Perfect 👍

**Review by florentlotthepro — DISMISSED** [review]

**Comment by lauthieb** [comment]
@florentlotthepro @baptistedajon is it ok to merge it soon? :)

**Review by florentlotthepro — DISMISSED** [review]

**Review by baptistedajon — APPROVED** [review]
🍫

**Review by florentlotthepro — APPROVED** [review]

**Review by baptistedajon — APPROVED** [review]
🍆

**Review by florentlotthepro — DISMISSED** [review]

**Review by florentlotthepro — APPROVED** [review]

**Review by florentlotthepro — APPROVED** [review]

**Pull request merged**
