### PR TITLE
feat: update icons

### PR DESCRIPTION
**Pull request by lauthieb**
**Automated Pull Request to update icons.**

### CODE REVIEW

**Comment by daniel-dumortier** [comment]
If `Vitamix` is now a generated class, we should maybe add it to `sonar.cpd.exclusions` to avoid quality date failure on Sonar du to code duplication

**Comment by lauthieb** [comment]
@florentlotthepro Can you rename `IconModel+Sections.swift` to `IconsModel+Sections.swift` in order to align with the existing file called `IconsModel.swift`? Thanks.

@mackoj for your info

**Comment by florentlotthepro** [comment]
@lauthieb Fixed 🙂

**Comment by lauthieb** [comment]
Thanks @florentlotthepro!

@daniel-dumortier @mackoj can we please have your review in order to merge this PR? 🙏

**Pull request merged**
