### PR TITLE
feat: swiftui vitamin textfield

### LINKED ISSUE #99: feat: add text input component
**New component**

- add `text input` component for SwiftUI.

**Documentation links**

- [Documentation](https://www.decathlon.design/726f8c765/v/0/p/31121d-text-input/b/68557b)
- [Figma](https://www.figma.com/file/cmZCNVet64UlDNnDDd4hDV/Vitamin---iOS-14-UI-kit-(v0)?node-id=2862%3A9708)

### PR DESCRIPTION
**Pull request by florentlotthepro**
## Changes description

Add text input component to SwiftUI.

## Context

- Closes #99 

## Checklist

- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on an iPhone device/simulator.
- [x] I have tested on an iPad device/simulator.
- [x] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- No, but there are some deprecated values:
    - `outline` style is renamed `outlined`.
    - `VitaminTextField.Style` is renamed `VitaminTextFieldStyle`.
    - `VitaminTextField.State` is renamed `VitaminTextFieldState`.

#### iPhone

| Outlined | Filled |
| -------- | ------ |
| Simulator Screen Shot - iPhone 14 - 2022-12-08 at 16 06 46 | Simulator Screen Shot - iPhone 14 - 2022-12-08 at 16 06 52 |

#### iPad

| Outlined | Filled |
| -------- | ------ |
| Simulator Screen Shot - iPad Pro (9 7-inch) - 2022-12-08 at 16 08 01 | Simulator Screen Shot - iPad Pro (9 7-inch) - 2022-12-08 at 16 08 05 |

## Other information

Co-authored-by: @MBarantal
Co-authored-by: @baptistedajon

### CODE REVIEW

**Review by baptistedajon — DISMISSED** [review]
Nice !

**Review by daniel-dumortier — COMMENTED** [review]
Everything seems ok to me on a code point of view.
I just spotted some typos (some of them were already in the code or doc I wrote on UIKit side)
But when I launch the showcase, TextField in the 'states' section are not editable (I can not enter text in them), which is hopefully not the intended behavior.

Another remark, I think that could be a plus to add a demo of the 'password' use case (toggling between TextField and SecureTextField by clicking on icon) in the showcase because I think it may be a common use case, and that could help devs to have an example (I did it on UIKit side)

**Review by baptistedajon — APPROVED** [review]

**Review by daniel-dumortier — APPROVED** [review]
OK, I misunderstood your goal in showcase.
For password, I think it could be discussed with designers, because that is the way they design such password input fields in their designs (and in other platforms, like for example on Decathlon Login's web page)

**Review by baptistedajon — DISMISSED** [review]

**Review by daniel-dumortier — APPROVED** [review]
👍

**Comment by florentlotthepro** [comment]
Feedback from the design review:
> The color of the placeholders here seems very clear, I'm not sure if it is "content tertiary"?   

It's a system color that we cannot customize -> Need a design update for iOS.

Ready to merge ✅

**Pull request merged**
